# Dictionary labels
txtTitle = "Who's talking"
txtBot = "Bot name"
txtAuth = "OAUTH token"
txtChannel = "Channel name"
txtNotConnd = "Not Connected"
txtListChat = "\nList of chatters"
txtIgnore = "Ignore"
txtConnd = "Connected"
txtStart = "Start"
txtStop = "Stop"
txtClear = "Clear"
txtConnect = "Connect"
txtConnecting = "Connecting"
txtDisconnect = "Disconnect"
txtError = "Error"
txtErrorBot = "Bot name different from oauth"
txtErrorChannel = "Could not connect to channel"
txtErrorOauth = "Improperly formatted auth"
txtErrorAuthenticationFailed = "Login authentication failed"
txtErrorNoData = "Set bot and channel & click connect."
txtSave = "Save file"
txtSettings = "Settings"
txtHelloMode = "Hello Mode"
txtJoinMode = "Join Mode"
txtJoinPick = "Pick"
txtNamePoolOpen = "Name pool open! Type !join to join!"

# tk helpers
TXT = "text"
END = "end"
FG = "fg"
RD = "red"
BL = "blue"
GR = "gray"
ON = "normal"
OFF = "disabled"
