# Dictionary labels
txtTitle = "Who\'s talking"
txtBot = "Bot name"
txtAuth= "OAUTH token"
txtChannel = "Channel name"
txtNotConnd = "Not Connected"
txtListChat = "\nList of chatters"
txtIgnore = "Ignore"
txtConnd = "Connected"
txtStart = "Start"
txtStop = "Stop"
txtClear = "Clear"
txtConnect = "Connect"
txtDisconnect = "Disconnect"
txtError = "Error"

# tk helpers
TXT = "text"
END = "end"
FG = "fg"
RD = "red"
BL = "blue"
RSD = "raised"
SKN = "sunken"
